[package]
name = "meadow"
version = "0.1.0"
authors = ["Mikael SilvÃ©n <mikael@silven.nu>"]

[dependencies.glium]
version = "*"
features = ["cgmath"]

[dependencies]
glutin = "*"
genmesh = "*"
clock_ticks = "*"
obj = "*"
cgmath = "*"
image = "*"
rand = "*"
num = "*"
